### ISSUE TITLE
emulator not found when opening pcsx2 in standalone emulationstation-de

### ISSUE THREAD

**Issue by subtrusion** [EmuDeck/emudeck-we#1]
hey emudeck team,

was playing with pcsx2 and opening via emulationstation-de instead of direct through steam and noticed an emulator not found error. looks like the command in the systems config and the paths to the emulator are a little off. i'm not sure where in the setup script the break takes place, but if it helps my fix to the installed configurations are below:

1. the qt version of pcsx2 uses "-nogui" instead of "--nogui" [https://wiki.pcsx2.net/index.php/Command-line_support](https://wiki.pcsx2.net/index.php/Command-line_support#:~:text=options%20(this%20list).-,General%20Options%20QT,-Usage%3A%20pcsx2%2Dqtx64)
file: INSTALL-DRIVE:\Emulation\tools\EmulationStation-DE\resources\systems\windows\es_systems.xml
line: 972 <command label="PCSX2 (Standalone)">%EMULATOR_PCSX2% ~~--nogui~~  **-nogui -fastboot -fullscreen** %ROM%</command>

3. The executable points to the non-qt version of pcsx2, but the qt version is installed
file: INSTALL-DRIVE:\Emulation\tools\EmulationStation-DE\resources\systems\windows\es_find_rules.xml
line: 125 <entry>%ESPATH%\PCSX2\ ~~pcsx2.exe~~ **pcsx2-qtx64-avx2.exe**</entry>
line: 126 <entry>%ESPATH%\Emulators\PCSX2\ ~~pcsx2.exe~~ **pcsx2-qtx64-avx2.exe**</entry>
line: 127 <entry>%ESPATH%\..\PCSX2\ ~~pcsx2.exe~~ **pcsx2-qtx64-avx2.exe**</entry>

hope this helps

**Comment by Godsbane** [comment]
Is the alternate emulator set correctly?

One is for wx and one is for qt

**Comment by Godsbane** [comment]
Right I meant in es-de, there's an alternate emulator setting. Just curious what it was set to.

**Comment by dragoonDorise** [comment]
Hi @subtrusion, we've reported this to the EmulationStation team! thanks for opening the issue. We'll get back as soon as they fix it on their end

**Comment by leonstyhre** [comment]
I'm not sure I understand the problem, these are the es_find_rules.xml entries for PCSX2:

``` 
   <emulator name="PCSX2">
        <!-- Sony PlayStation 2 emulator PCSX2 -->
        <rule type="staticpath">
            <entry>%ESPATH%\Emulators\PCSX2-Qt\pcsx2-qtx64*.exe</entry>
            <entry>%ESPATH%\PCSX2-Qt\pcsx2-qtx64*.exe</entry>
            <entry>%ESPATH%\..\PCSX2-Qt\pcsx2-qtx64*.exe</entry>
        </rule>
    </emulator>
    <emulator name="PCSX2-LEGACY">
        <!-- Sony PlayStation 2 emulator PCSX2 (legacy) -->
        <rule type="staticpath">
            <entry>%ESPATH%\Emulators\PCSX2\pcsx2.exe</entry>
            <entry>%ESPATH%\PCSX2\pcsx2.exe</entry>
            <entry>%ESPATH%\..\PCSX2\pcsx2.exe</entry>
        </rule>
    </emulator>
```

And this is the ps2 entry in es_systems.xml:

```
    <system>
        <name>ps2</name>
        <fullname>Sony PlayStation 2</fullname>
        <path>%ROMPATH%\ps2</path>
        <extension>.bin .BIN .chd .CHD .ciso .CISO .cso .CSO .dump .DUMP .elf .ELF .gz .GZ .m3u .M3U .mdf .MDF .img .IMG .iso .ISO .isz .ISZ .ngr .NRG</extension>
        <command label="PCSX2">%EMULATOR_RETROARCH% -L %CORE_RETROARCH%\pcsx2_libretro.dll %ROM%</command>
        <command label="PCSX2 (Standalone)">%EMULATOR_PCSX2% -batch %ROM%</command>
        <command label="PCSX2 Legacy (Standalone)">%EMULATOR_PCSX2-LEGACY% --nogui %ROM%</command>
        <command label="Play! (Standalone)">%EMULATOR_PLAY!% --disc %ROM%</command>
        <platform>ps2</platform>
        <theme>ps2</theme>
    </system>
```

There is no -nogui or --nogui flag set for the Qt release of PCSX2.
