### ISSUE TITLE
Recommended approach for sharing Roms directory/device in dual-boot setups

### ISSUE THREAD

**Issue by felipejfc** [EmuDeck/emudeck-we#12]
So I'm dual booting windows and chimeraos in my ROG Ally and I would like to share the same data/roms folder between both systems. I thought about 2 possible approaches, can you let me know if they would work, or if you recommend another path:

Formatting the SD Card in exfat that's supported by both OSes
Using software to mount the ext4 partition in windows
If I go for 2, how do I reconfigure my existing installation to point to it? Do I need to reinstall emudeck?

**Comment by dragoonDorise** [comment]
Hi @felipejfc we don't have an official solution for this.

Using Exfat won't work on SteamOS, you need ext4

**Comment by felipejfc** [comment]
I ended up creating a ntfs partition and mounting in linux using ntfs-3g. I need to manually create some links to make roms be mapped properly, and also saves, because of the differences in directory scheme. It's hacky but it works

**Comment by ch3vr0n5** [comment]
> I ended up creating a ntfs partition and mounting in linux using ntfs-3g. I need to manually create some links to make roms be mapped properly, and also saves, because of the differences in directory scheme. It's hacky but it works

I know I'm late to this party, but I find that a btrfs partition is much more efficient than using NTFS. It's fairly easy to setup winbtrfs with a couple registry entries along with your UID and GID from SteamOS.
