### ISSUE TITLE
Shortcut files should be perhaps instead symlinks?

### ISSUE THREAD

**Issue by anaisbetts** [EmuDeck/emudeck-we#14]
I notice that a lot of tooling in here seems to create Shortcuts (.lnk files) - these files are not parsed by the filesystem or PowerShell et al, they only work when invoked via Windows Explorer (i.e. double clicking on a .lnk to a folder will take you to that folder).

Instead, you likely want to create either a Symbolic Link or a Junction Point. Symlinks on Windows 10 can only be created via elevated admin, and we don't need relative paths or symlinks to files inside the target, so Junction Points are likely the best bet. We can create these via `mklink /D` or via `New-Item -Name <link> -ItemType Junction -Value <source>`.

This will result in path traversal that's more similar to what we'd expect on Linux (i.e. `dir C:\Emulation\saves\retroarch\saves\*.srm` will now return what we expect)

**Comment by dragoonDorise** [comment]
HI @anaisbetts, I agree, that's why this has been already done on our dev builds, it will go live on the next release :)

Thanks!

**Comment by dragoonDorise** [comment]
@anaisbetts we just converted all .lnk to symlinks, closing the issue :)
