### ISSUE TITLE
[Bug] Invalid symlinks are not repaired by auto-repair or reinstall actions

### ISSUE THREAD

**Issue by Mellified** [EmuDeck/emudeck-we#17]
Steps to reproduce:
1. Install EmuDeck to a drive (C:)
2. Re-install EmuDeck to a different drive (D:)

At this point, the Yuzu Symlinks at `%USERPROFILE%\emudeck\EmulationStation-DE\Emulators\yuzu-windows-msvc\user\nand\system\Contents\registered` and `%USERPROFILE%\emudeck\EmulationStation-DE\Emulators\yuzu-windows-msvc\user\keys` incorrectly point to `C:\Emulation\bios\yuzu\firmware` and `C:\Emulation\bios\yuzu\keys`. This state is detected by the BIOS checker as Switch BIOS files are missing. However, the self-repair and EmuDeck reinstall actions do not fix the configuration. It would be useful to re-create the symlinks during both actions.

**Comment by dragoonDorise** [comment]
this should be fixed
