### ISSUE TITLE
[Bug] Invalid Steam shortcut to EmulationStation DE is not repaired

### ISSUE THREAD

**Issue by Mellified** [EmuDeck/emudeck-we#19]
Similar to https://github.com/EmuDeck/emudeck-we/issues/17 , the Steam shortcut for EmulationStation DE is not re-created during auto repair or reinstall.

The Steam shortcut points to:
`"C:\Windows\System32\cmd.exe" /k start /max "Loading PowerShell Launcher" "C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -File C:\Emulation\tools\launchers\esde\EmulationStationDE.ps1 && exit " && exit --emudeck`

**Comment by dragoonDorise** [comment]
This was fixed some time ago
