### ISSUE TITLE
Dolphin not found when started within Steam

### ISSUE THREAD

**Issue by Paki64** [EmuDeck/emudeck-we#2]
Hi, I think I found a little error in the Dolphin shortcuts configuration, probably a typo.

While in emulationstation-de and SRM everything is fine, the Dolphin shortcut located in \\Emulation\\tools\launchers has an incorrect path:
The path configured is "\\Emulation\\tools\EmulationStation-DE\Emulators\Dolphin-x64\Dolphin-emu.exe", which is an empty folder, instead of "\\Emulation\\tools\EmulationStation-DE\Emulators\Dolphin-x64\Dolphin.exe", which is, infact, the one used by ES and SRM.

Thanks for the support

**Comment by dragoonDorise** [comment]
Hi @Paki64 , fixed!!

Thanks :)
