### ISSUE TITLE
[Enhancement] Use the same path for EmulationStation DE metadata on Linux and Windows

### ISSUE THREAD

**Issue by Mellified** [EmuDeck/emudeck-we#22]
Currently EmulationStation DE for Windows uses the path `Emulation\storage\downloaded_media\` under the configured EmuDeck drive. EmulationStation DE on SteamDeck uses `Emulation\tools\downloaded_media\`. Neither is the default ESDE path for metadata. Using the same path on both platforms allows sharing metadata when cloning or synching EmuDeck data.

**Comment by shawntabrizi** [comment]
+1 just ran into this today

There is also another user on reddit who reported the same: https://www.reddit.com/r/EmuDeck/comments/17onc1w/emudeck_seems_to_install_the_emulation_station/

**Comment by shawntabrizi** [comment]
Seems like the solution might be simply changing:

https://github.com/EmuDeck/emudeck-we/blob/2a6f9136e73f93c5b76cf3952ece36d36570e0b5/configs/emulationstation/es_settings.xml#L3

**Comment by dragoonDorise** [comment]
this was moved to storage, same as linux some time ago
