### ISSUE TITLE
[Bug] Unnecessary white space

### ISSUE THREAD

**Issue by brisma** [EmuDeck/emudeck-we#23]
Hello, there are some unnecessary blanks which result in strings in settings.ps1 such as "1440P " instead of "1440P".

https://github.com/EmuDeck/emudeck-we/blob/c8bb8059fca5ab5b6a9ff7deb044f53db01724e6/functions/JSONtoPS1.ps1#L233-L237

**Comment by dragoonDorise** [comment]
Fixed!
