### ISSUE TITLE
[Bug] RPCS3 Resolution Scale not working

### ISSUE THREAD

**Issue by brisma** [EmuDeck/emudeck-we#24]
With the arrival of Lenovo Legion Go and ROG Ally, it might make sense to reintroduce resolution scaling on RPCS3 as well (after fixing bug #23).

https://github.com/EmuDeck/emudeck-we/blob/c8bb8059fca5ab5b6a9ff7deb044f53db01724e6/functions/EmuScripts/emuDeckRPCS3.ps1#L19-L19

**Comment by dragoonDorise** [comment]
@brisma , fixed!
