### ISSUE TITLE
many many UAC prompts

### ISSUE THREAD

**Issue by nascentt** [EmuDeck/emudeck-we#25]
Have had Emudeck installed on windows few a few months now.  I just fired it up and let it update itself, only this time it spawned dozens of powershell windows with UAC, at least 50, maybe 100?  I had to accept the UAC prompt each time rather than a one-off UAC prompt at the start of the update.  I think updates should probably spawn a single admin process, and child processes can spawn off of that to prevent needing so many manual user prompts.

**Comment by nascentt** [comment]
Just realised emudeck has also reset to default now and shows the "Welcome to EmuDeck" screen and let's me choose to setup easy mode or custom mode, but I was already set up before this update.  the files still exist on my storage so I guess I'll just set everything up in custom mode again over the top.

**Comment by mirh** [comment]
Steam handles this with a dedicated service indeed

**Comment by dragoonDorise** [comment]
we removed all but one UAC prompt if I remember correctly, closing the issue :)
