### ISSUE TITLE
Duckstation Memcard & Savestate folders are not symlinked to Saves

### ISSUE THREAD

**Issue by Jacksaur** [EmuDeck/emudeck-we#34]
Noticed this while cloning my saves out of my old standalone emulator setup to be consolidated into EmuDeck's unified saves folder. (Fantastic feature, by the way!)

Duckstation does not have its memcards and savestates folders (located in the main Duckstation emulator folder) symlinked to the Emulation/saves/duckstation/saves or /states folders.

**Comment by dragoonDorise** [comment]
Hi, I don't remember when but this was fixed some time ago
