### ISSUE TITLE
Primehack is only partially downloaded

### ISSUE THREAD

**Issue by Jacksaur** [EmuDeck/emudeck-we#36]
Tried running Primehack after downloading the emulator and adding MTP to Steam. Script would fail almost immediately.
Checking the Emulators folder, it seems Primehack isn't being downloaded properly. The Primehack folder only possesses the User folder, which itself only contains the GameSettings, Config, and controller icon texture replacements. Nothing else of Dolphin, not even the main exe which the Powershell script tries to execute, is downloaded.

I've uninstalled and reinstalled Primehack a few times through the Emudeck UI, nothing else is downloaded other than these files.

Edit: Downloaded Primehack from their forum post myself and dropped the files in, adding a portable.txt. Steam Rom Manager's added entry for Metroid Prime Trilogy now starts fine and everything seems to work (Aside from the lack of a Symlinked save folder, of course). It seems that everything else regarding Primehack is in place, it's just the emulator files themselves.

**Comment by dragoonDorise** [comment]
Sorry I missed this, fixed!

**Comment by victoreebel** [comment]
Seem to be hitting the same/or similar issue on 2.2.18:

Primehack fails almost immediately after launching directly or via Steam.

Contents of `C:\Users\USER\EmuDeck\EmulationStation-DE\Emulators\PrimeHack`:

`d-----        28/07/2024     12:48                User
-a----        28/07/2024     13:09              0 portable.txt
------        03/05/2024     10:40       40026988 PrimeHack-sha[26beef4].tar.gz`
