### ISSUE TITLE
Steam Rom Manager is not Opening.

### ISSUE THREAD

**Issue by AHS12** [EmuDeck/emudeck-we#38]
Setup Emu deck. Trying to open steam rom manager but it is not opening steam.Emudeck is able to close the running steam but can not open steam by steam rom manager.

Device Info
Edition	Windows 11 Pro
Version	22H2
Installed on	‎11/‎27/‎2022
OS build	22621.3155
Experience	Windows Feature Experience Pack 1000.22684.1000.0

CPU: Ryzen 5 5600
GPU: RTX 3050
RAM: 32gb

here is the logs
[emudeck_logs.zip](https://github.com/EmuDeck/emudeck-we/files/14396718/emudeck_logs.zip)

**Comment by AHS12** [comment]
I also tried Opening steam rom manager Directly from start menu but same result.

**Comment by dragoonDorise** [comment]
sorry for answering so late, this was fixed some months ago
