### ISSUE TITLE
Git not installed via Winget

### ISSUE THREAD

**Issue by WingofaGriffin** [EmuDeck/emudeck-we#39]
`winget install -e --id Git.Git` should be in the setup somewhere probably. We've already using it for a few other apps, so shouldn't be an issue.

**Comment by jnichols35** [comment]
@WingofaGriffin Git is already being installed via winget: https://github.com/EmuDeck/emudeck-we/blob/cfcab24dba99c777c8705b4b146733bbb38f4f11/install.ps1#L431-L433

It also attempts to install git manually if winget fails: https://github.com/EmuDeck/emudeck-we/blob/cfcab24dba99c777c8705b4b146733bbb38f4f11/install.ps1#L435-L471
