### ISSUE TITLE
Steam ROM Manager does not parse several platforms

### ISSUE THREAD

**Issue by QuaiGoner** [EmuDeck/emudeck-we#42]
There is a problem that Steam Rom Manager does not parse several platforms for me if i use Steam as a frontend, for example

- nes
- snes
- n64
- dreamcast
- megadrive
- gamecube
- j2me

Roms are in theirs corresponding folders

![image](https://github.com/EmuDeck/emudeck-we/assets/41058180/fedc1149-be0a-44c9-a53c-46db9eaa254b)
![image](https://github.com/EmuDeck/emudeck-we/assets/41058180/0980aa41-b087-4eab-a491-ae4db3339fe1)

**Comment by jordandrako** [comment]
Same here, I see there are many parser configs missing the `Emulation\tools\userData\parsers` folder. Most of the RetroArch parsers aren't downloaded.

**Comment by dragoonDorise** [comment]
fix promoted to main
