### ISSUE TITLE
Emulator save folders not properly getting symlinks to the EmuDeck Install\saves folder

### ISSUE THREAD

**Issue by PMahern** [EmuDeck/emudeck-we#49]
I've been gaming a bit with EmuDeck but had never set up cloud sync so I already have a few saves floating around on my handheld. I also hadn't bothered to update emudeck/reset configurations for a while. After setting up cloud sync with nextcloud and running reset configurations I saw the folders created in the saves folder and the data synced up properly to the server. However, subsequent saves were not being picked up by the cloud sync. After some investigating it seems like the symbolic links that point from each respective emulator's save folder to the newly created "$emudeckinstallation\saves" folder are not being created, instead the original folders are copied to the saves folder but still left in their original location as well and the emulator just continues on normally with the saves in the original location.

**Comment by dragoonDorise** [comment]
fix promoted to main
