### ISSUE TITLE
Retroarch Hotkeys are missing Start/Select modifiers.

### ISSUE THREAD

**Issue by Jacksaur** [EmuDeck/emudeck-we#51]
All hotkeys in Retroarch are bound to the same buttons as regular input. They are not bound to multiple-inputs like in the documentation. A takes screenshots, B pauses the game, and all Savestate inputs conflict with each other, since they depend on Select or Start alternatively.
This issue persists after a config reset, and fresh install.

**Comment by dragoonDorise** [comment]
Hi @Jacksaur we don't have implemented hotkeys using the start button on RA, only with select

**Comment by Jacksaur** [comment]
Huh, when I made the issue the hotkeys were going off even without me holding the select button.
But after fully reinstalling every part of Emudeck from scratch and redoing the SRM import, everything's fine again: Hotkeys only firing when Select is held.
Thanks anyway!
