### ISSUE TITLE
Installation gets stuck on creating symlinks

### ISSUE THREAD

**Issue by Bboy486** [EmuDeck/emudeck-we#55]
As it says when I'm running this on Windows the installation get stuck on creating symlink. I can cancel that part and then a few scripts run it looks like it finishes however I am not sure why it freezes at that point. 

Also I think this is causing an issue with the Emudeck plug in for playnite.

**Comment by Howell-Ding** [comment]
Was is stuck on creating Xenia save links? If so, try open "C:\Users\XXX\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckXenia.ps1" and edit Line 26 to "mkdir "$emusPath\xenia\"  -ErrorAction SilentlyContinue" ,then reinstall Emudeck.

**Comment by visionexbx** [comment]
> Was is stuck on creating Xenia save links? If so, try open "C:\Users\XXX\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckXenia.ps1" and edit Line 26 to "mkdir "$emusPath\xenia" -ErrorAction SilentlyContinue" ,then reinstall Emudeck.

I am stuck in the same place

**Comment by Howl-24** [comment]
> > Was is stuck on creating Xenia save links? If so, try open "C:\Users\XXX\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckXenia.ps1" and edit Line 26 to "mkdir "$emusPath\xenia" -ErrorAction SilentlyContinue" ,then reinstall Emudeck.
> 
> I am stuck in the same place

Delete "C:\Users\XXX\AppData\Roaming\EmuDeck\EmulationStation-DE\Emulators\xenia\content" and then reinstall, this path is conflicted with the symlink that installation script about to creat.
