### ISSUE TITLE
Primehack doesn't install fully

### ISSUE THREAD

**Issue by victoreebel** [EmuDeck/emudeck-we#61]
Possibly related to https://github.com/EmuDeck/emudeck-we/issues/36

Contents of C:\Users\USER\EmuDeck\EmulationStation-DE\Emulators\PrimeHack after a fresh install of latest software:

    d----- 28/07/2024 12:48 User
    -a---- 28/07/2024 13:09 0 portable.txt
    ------ 03/05/2024 10:40 40026988 PrimeHack-sha[26beef4].tar.gz

No dolphin.exe is present so the ps1 script fails on launch.

**Comment by victoreebel** [comment]
https://github.com/EmuDeck/emudeck-we/blob/main/functions/EmuScripts/emuDeckPrimehack.ps1 References a .zip file correctly, but the web release version pulls this tar.gz

**Comment by BonQerss** [comment]
bump, not fixed in latest release

**Comment by dragoonDorise** [comment]
Fixed in 2.3
